Pytest travis
megajanlott/cbor-decoder pull request #28
Opened 2017-03-21 23:16 UTC by gemabarni

This pr adds continuous integration with travis and testing capability with pytest.

2017-03-21 23:35 UTC, gerhardberger requested changes

2017-03-21 23:35 UTC, gerhardberger commented on README.md
> +$ pip install -U pytest
I think we should be using `pip3` here. At least that what succeeded for me installing.

2017-03-21 23:35 UTC, gerhardberger commented on README.md
> +$ pytest
After installing there was no `pytest` command for me. Is there some other way to install or run the tests?

2017-03-21 23:35 UTC, gerhardberger commented on README.md
> +Please use the naming convention `test_*.py` for test files, as this is the required format for pytest.
We can omit the 'Please' here. 😄

2017-03-22 00:55 UTC, gemabarni commented on README.md
> +$ pip install -U pytest
It is more of a convention. `pip` always uses the default python version. Probably it is python2 in your case. Replaced it with `pip3` though, just to make sure everyone uses python3.

2017-03-22 00:56 UTC, gemabarni commented on README.md
> +$ pytest
Fixed it, now it runs with `python scripts/test.py` as well.

2017-03-22 00:57 UTC, gemabarni commented on README.md
> +Please use the naming convention `test_*.py` for test files, as this is the required format for pytest.
I was just trying to be a nice guy 😢

2017-03-22 07:37 UTC, gerhardberger approved these changes

2017-03-22 07:37 UTC, merged